### ISSUE TITLE
VPG dataset

### ISSUE THREAD

**Issue by cvchanghao** [PrabhuSM16/VPGNet-Pytorch#2]
Thank you for sharing! 
Can you share the dataset?

**Comment by doem97** [comment]
Thank you, I think you can get  VPGNet dataset at [https://github.com/SeokjuLee/VPGNet#vpgnet-dataset](VPGNet dataset @SeokjuLee) and run a test on CAFFE. The VPGNet team have implemented VPGNet on CAFFE, and our project here is to build the net on PyTorch. Our leader @PrabhuSM16 also implemented dataloader for VPGNet format dataset. Glad to have you noticing our latest updates. The whole project will be finished soon.

**Comment by doem97** [comment]
> Thank you for sharing!
> Can you share the dataset?

Thank you, I think you can get VPGNet dataset at [https://github.com/SeokjuLee/VPGNet#vpgnet-dataset](VPGNet dataset @SeokjuLee) and run a test on CAFFE. The VPGNet team have implemented VPGNet on CAFFE, and our project here is to build the net on PyTorch. Our leader @PrabhuSM16 also implemented dataloader for VPGNet format dataset. Glad to have you noticing our latest updates. The whole project will be finished soon.

**Comment by doem97** [comment]
> Thank you for sharing!
> Can you share the dataset?

Thank you, I think you can get VPGNet dataset at [VPGNet dataset @SeokjuLee ](https://github.com/SeokjuLee/VPGNet#vpgnet-dataset) and run a test on CAFFE. The VPGNet team have implemented VPGNet on CAFFE, and our project here is to build the net on PyTorch. Our leader @PrabhuSM16 also implemented dataloader for VPGNet format dataset. Glad to have you noticing our latest updates. The whole project will be finished soon.

**Comment by cvchanghao** [comment]
Thanks！ I will follow this project.
I noticed the "vpgnet_model.py". As in the paper, what does the **tiling layer** for? What about just replace it by a normal convolutional layer?

**Comment by doem97** [comment]
> Thanks！ I will follow this project.
> I noticed the "vpgnet_model.py". As in the paper, what does the **tiling layer** for? What about just replace it by a normal convolutional layer?

I think can work. Tilling layer is their designed layer, for which they didn't explained in details. It works like:
![image](https://user-images.githubusercontent.com/19631039/107602261-e1282a00-6c63-11eb-8c0d-b13f1c9f3fea.png)
