### ISSUE TITLE
Why multiLabel has 64 channels?

### ISSUE THREAD

**Issue by cvchanghao** [PrabhuSM16/VPGNet-Pytorch#3]
Hi! I am also doing this project now. But with some questions.
Why multiLabel has 64 channels? Did you figured it out?
Shall I have your email or something to communicate？
Thank you！

**Comment by doem97** [comment]
Hey, they only use the first 18 channels as 18 classes of lanes & Roadmarkings in fact. Other 64-18 channels are not used.

**Comment by doem97** [comment]
> Hi! I am also doing this project now. But with some questions.
> Why multiLabel has 64 channels? Did you figured it out?
> Shall I have your email or something to communicate？
> Thank you！

Hey, you are right. In fact, they only use the first 18 channels as 18 classes of lanes & Road marking. Other 64-18 channels are not used.
